language: python
branches:
only:
  - master
python:
  - "3.4"

cache:
  directories:
      - $HOME/.pip-cache/

addons:
  apt:
    packages:
        - gfortran 
        - libopenblas-dev
        - liblapack-dev
        - cmake

before_install:
  - sudo pip install conda
  - sudo conda init
  - sudo conda update conda --yes
  - deps='numpy nose scipy'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH

install:
  - pip install --upgrade pip
  - python setup.py install

script: 
  - python -c 'import BioExt'
  - cd tests && nosetests uds.py

notifications:
    email:
        recipients:
            - sweaver@temple.edu
        on_success: always
        on_failure: always

after_success:
  - coveralls
