language: python
branches:
only:
  - master
python:
  - "3.4"

cache:
  directories:
      - $HOME/.pip-cache/

addons:
  apt:
    packages:
        - gfortran 
        - libopenblas-dev
        - liblapack-dev
        - cmake

before_install:
  - pip install numpy
  - pip install biopython

install:
  - python setup.py install

script: 
  - python -c 'import BioExt'
  - nosetests tests/uds.py
  - nosetests tests/bam2msa.py
  - nosetests tests/tn93.py

notifications:
    email:
        recipients:
            - sweaver@temple.edu
            - spond@temple.edu
        on_success: always
        on_failure: always

after_success:
  - coveralls
